// <auto-generated />
using System;
using Medley.Collector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medley.Collector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029135552_AddSourceDetail")]
    partial class AddSourceDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ApiKeyMeetingTranscript", b =>
                {
                    b.Property<int>("ApiKeysId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingTranscriptsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApiKeysId", "MeetingTranscriptsId");

                    b.HasIndex("MeetingTranscriptsId");

                    b.ToTable("MeetingTranscriptApiKeys", (string)null);
                });

            modelBuilder.Entity("Medley.Collector.Data.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Medley.Collector.Data.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Medley.Collector.Data.MeetingTranscript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LengthInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Participants")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranscriptLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("MeetingTranscripts");
                });

            modelBuilder.Entity("ApiKeyMeetingTranscript", b =>
                {
                    b.HasOne("Medley.Collector.Data.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medley.Collector.Data.MeetingTranscript", null)
                        .WithMany()
                        .HasForeignKey("MeetingTranscriptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
