// <auto-generated />
using System;
using Medley.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Medley.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219212256_AddArticleVersioning")]
    partial class AddArticleVersioning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindingInsight", b =>
            {
                b.Property<Guid>("FindingsId")
                    .HasColumnType("uuid")
                    .HasColumnName("findings_id");

                b.Property<Guid>("InsightsId")
                    .HasColumnType("uuid")
                    .HasColumnName("insights_id");

                b.HasKey("FindingsId", "InsightsId")
                    .HasName("pk_finding_insight");

                b.HasIndex("InsightsId")
                    .HasDatabaseName("ix_finding_insight_insights_id");

                b.ToTable("finding_insight", (string)null);
            });

            modelBuilder.Entity("FindingObservation", b =>
            {
                b.Property<Guid>("FindingsId")
                    .HasColumnType("uuid")
                    .HasColumnName("findings_id");

                b.Property<Guid>("ObservationsId")
                    .HasColumnType("uuid")
                    .HasColumnName("observations_id");

                b.HasKey("FindingsId", "ObservationsId")
                    .HasName("pk_finding_observation");

                b.HasIndex("ObservationsId")
                    .HasDatabaseName("ix_finding_observation_observations_id");

                b.ToTable("finding_observation", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("ArticleTypeId")
                    .HasColumnType("uuid")
                    .HasColumnName("article_type_id");

                b.Property<string>("Content")
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Metadata")
                    .HasColumnType("text")
                    .HasColumnName("metadata");

                b.Property<Guid?>("ParentArticleId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_article_id");

                b.Property<DateTimeOffset?>("PublishedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("published_at");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<string>("Summary")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("summary");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.HasKey("Id")
                    .HasName("pk_articles");

                b.HasIndex("ArticleTypeId")
                    .HasDatabaseName("ix_articles_article_type_id");

                b.HasIndex("ParentArticleId")
                    .HasDatabaseName("ix_articles_parent_article_id");

                b.ToTable("articles", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleType", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Icon")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("icon");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_article_types");

                b.ToTable("article_types", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleVersion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ArticleId")
                    .HasColumnType("uuid")
                    .HasColumnName("article_id");

                b.Property<string>("ContentDiff")
                    .HasColumnType("text")
                    .HasColumnName("content_diff");

                b.Property<string>("ContentSnapshot")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("content_snapshot");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid?>("CreatedById")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<int>("VersionNumber")
                    .HasColumnType("integer")
                    .HasColumnName("version_number");

                b.HasKey("Id")
                    .HasName("pk_article_versions");

                b.HasIndex("ArticleId")
                    .HasDatabaseName("ix_article_versions_article_id");

                b.HasIndex("CreatedById")
                    .HasDatabaseName("ix_article_versions_created_by");

                b.HasIndex("ArticleId", "CreatedAt")
                    .HasDatabaseName("ix_article_versions_article_id_created_at");

                b.HasIndex("ArticleId", "VersionNumber")
                    .IsUnique()
                    .HasDatabaseName("ix_article_versions_article_id_version_number");

                b.ToTable("article_versions", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Finding", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<float>("ConfidenceScore")
                    .HasColumnType("real")
                    .HasColumnName("confidence_score");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_findings");

                b.ToTable("findings", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Fragment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("ArticleId")
                    .HasColumnType("uuid")
                    .HasColumnName("article_id");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("category");

                b.Property<Guid?>("ClusteredIntoId")
                    .HasColumnType("uuid")
                    .HasColumnName("clustered_into_id");

                b.Property<DateTimeOffset?>("ClusteringProcessed")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("clustering_processed");

                b.Property<int?>("Confidence")
                    .HasColumnType("integer")
                    .HasColumnName("confidence");

                b.Property<string>("ConfidenceComment")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("confidence_comment");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(10000)
                    .HasColumnType("character varying(10000)")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Vector>("Embedding")
                    .HasColumnType("vector(2000)")
                    .HasColumnName("embedding");

                b.Property<bool>("IsCluster")
                    .HasColumnType("boolean")
                    .HasColumnName("is_cluster");

                b.Property<DateTimeOffset?>("LastModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_modified_at");

                b.Property<Guid?>("SourceId")
                    .HasColumnType("uuid")
                    .HasColumnName("source_id");

                b.Property<string>("Summary")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("summary");

                b.Property<string>("Title")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.HasKey("Id")
                    .HasName("pk_fragments");

                b.HasIndex("ArticleId")
                    .HasDatabaseName("ix_fragments_article_id");

                b.HasIndex("ClusteredIntoId")
                    .HasDatabaseName("ix_fragments_clustered_into_id");

                b.HasIndex("SourceId")
                    .HasDatabaseName("ix_fragments_source_id");

                b.ToTable("fragments", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Insight", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<int>("Priority")
                    .HasColumnType("integer")
                    .HasColumnName("priority");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("title");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_insights");

                b.ToTable("insights", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Integration", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ApiKey")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("api_key");

                b.Property<string>("BaseUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("base_url");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("DisplayName")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_name");

                b.Property<bool>("InitialSyncCompleted")
                    .HasColumnType("boolean")
                    .HasColumnName("initial_sync_completed");

                b.Property<DateTimeOffset?>("LastHealthCheckAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_health_check_at");

                b.Property<DateTimeOffset?>("LastModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_modified_at");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_integrations");

                b.ToTable("integrations", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Observation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("category");

                b.Property<float>("ConfidenceScore")
                    .HasColumnType("real")
                    .HasColumnName("confidence_score");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(8000)
                    .HasColumnType("character varying(8000)")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Vector>("Embedding")
                    .HasColumnType("vector(2000)")
                    .HasColumnName("embedding");

                b.Property<DateTimeOffset?>("LastModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_modified_at");

                b.Property<Guid?>("ObservationClusterId")
                    .HasColumnType("uuid")
                    .HasColumnName("observation_cluster_id");

                b.Property<string>("SourceContext")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("source_context");

                b.Property<Guid?>("SourceId")
                    .HasColumnType("uuid")
                    .HasColumnName("source_id");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_observations");

                b.HasIndex("ObservationClusterId")
                    .HasDatabaseName("ix_observations_observation_cluster_id");

                b.HasIndex("SourceId")
                    .HasDatabaseName("ix_observations_source_id");

                b.ToTable("observations", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.ObservationCluster", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_observation_clusters");

                b.ToTable("observation_clusters", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Organization", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("EmailDomain")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("email_domain");

                b.Property<bool>("EnableSmartTagging")
                    .HasColumnType("boolean")
                    .HasColumnName("enable_smart_tagging");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_organizations");

                b.ToTable("organizations", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTimeOffset?>("Date")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date");

                b.Property<string>("ExternalId")
                    .HasMaxLength(400)
                    .HasColumnType("character varying(400)")
                    .HasColumnName("external_id");

                b.Property<string>("ExtractionMessage")
                    .HasColumnType("text")
                    .HasColumnName("extraction_message");

                b.Property<int>("ExtractionStatus")
                    .HasColumnType("integer")
                    .HasColumnName("extraction_status");

                b.Property<Guid>("IntegrationId")
                    .HasColumnType("uuid")
                    .HasColumnName("integration_id");

                b.Property<bool?>("IsInternal")
                    .HasColumnType("boolean")
                    .HasColumnName("is_internal");

                b.Property<string>("MetadataJson")
                    .HasColumnType("text")
                    .HasColumnName("metadata_json");

                b.Property<int>("MetadataType")
                    .HasColumnType("integer")
                    .HasColumnName("metadata_type");

                b.Property<string>("Name")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<DateTimeOffset?>("TagsGenerated")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("tags_generated");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_sources");

                b.HasIndex("IntegrationId")
                    .HasDatabaseName("ix_sources_integration_id");

                b.ToTable("sources", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Tag", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("SourceId")
                    .HasColumnType("uuid")
                    .HasColumnName("source_id");

                b.Property<Guid?>("TagOptionId")
                    .HasColumnType("uuid")
                    .HasColumnName("tag_option_id");

                b.Property<Guid>("TagTypeId")
                    .HasColumnType("uuid")
                    .HasColumnName("tag_type_id");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("value");

                b.HasKey("Id")
                    .HasName("pk_tags");

                b.HasIndex("TagOptionId")
                    .HasDatabaseName("ix_tags_tag_option_id");

                b.HasIndex("TagTypeId")
                    .HasDatabaseName("ix_tags_tag_type_id");

                b.HasIndex("SourceId", "TagTypeId")
                    .IsUnique()
                    .HasDatabaseName("ix_tags_source_id_tag_type_id");

                b.ToTable("tags", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.TagOption", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("TagTypeId")
                    .HasColumnType("uuid")
                    .HasColumnName("tag_type_id");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("value");

                b.HasKey("Id")
                    .HasName("pk_tag_options");

                b.HasIndex("TagTypeId", "Value")
                    .IsUnique()
                    .HasDatabaseName("ix_tag_options_tag_type_id_value");

                b.ToTable("tag_options", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.TagType", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<bool>("IsConstrained")
                    .HasColumnType("boolean")
                    .HasColumnName("is_constrained");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<string>("Prompt")
                    .HasColumnType("text")
                    .HasColumnName("prompt");

                b.Property<int>("ScopeUpdateMode")
                    .HasColumnType("integer")
                    .HasColumnName("scope_update_mode");

                b.HasKey("Id")
                    .HasName("pk_tag_types");

                b.HasIndex("Name")
                    .IsUnique()
                    .HasDatabaseName("ix_tag_types_name");

                b.ToTable("tag_types", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.Template", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("description");

                b.Property<DateTimeOffset?>("LastModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_modified_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_templates");

                b.ToTable("templates", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer")
                    .HasColumnName("access_failed_count");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text")
                    .HasColumnName("concurrency_stamp");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("email");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("email_confirmed");

                b.Property<string>("FullName")
                    .HasColumnType("text")
                    .HasColumnName("full_name");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<DateTimeOffset?>("LastModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_modified_at");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("lockout_enabled");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("lockout_end");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_email");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_user_name");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text")
                    .HasColumnName("password_hash");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text")
                    .HasColumnName("phone_number");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("phone_number_confirmed");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("text")
                    .HasColumnName("security_stamp");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("two_factor_enabled");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("user_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_users");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("Medley.Domain.Entities.UserAuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Action")
                    .HasColumnType("integer")
                    .HasColumnName("action");

                b.Property<string>("Details")
                    .HasColumnType("text")
                    .HasColumnName("details");

                b.Property<string>("IpAddress")
                    .HasMaxLength(45)
                    .HasColumnType("character varying(45)")
                    .HasColumnName("ip_address");

                b.Property<bool>("Success")
                    .HasColumnType("boolean")
                    .HasColumnName("success");

                b.Property<DateTimeOffset>("Timestamp")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("timestamp");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("user_name");

                b.HasKey("Id")
                    .HasName("pk_user_audit_logs");

                b.HasIndex("Action")
                    .HasDatabaseName("ix_user_audit_logs_action");

                b.HasIndex("Timestamp")
                    .HasDatabaseName("ix_user_audit_logs_timestamp");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_user_audit_logs_user_id");

                b.ToTable("user_audit_logs", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_roles");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_role_claims");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_role_claims_role_id");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_user_claims");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_claims_user_id");

                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("text")
                    .HasColumnName("login_provider");

                b.Property<string>("ProviderKey")
                    .HasColumnType("text")
                    .HasColumnName("provider_key");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("text")
                    .HasColumnName("provider_display_name");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("LoginProvider", "ProviderKey")
                    .HasName("pk_asp_net_user_logins");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_logins_user_id");

                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid")
                    .HasColumnName("role_id");

                b.HasKey("UserId", "RoleId")
                    .HasName("pk_asp_net_user_roles");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_user_roles_role_id");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("LoginProvider")
                    .HasColumnType("text")
                    .HasColumnName("login_provider");

                b.Property<string>("Name")
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<string>("Value")
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("UserId", "LoginProvider", "Name")
                    .HasName("pk_asp_net_user_tokens");

                b.ToTable("AspNetUserTokens", (string)null);
            });

            modelBuilder.Entity("FindingInsight", b =>
            {
                b.HasOne("Medley.Domain.Entities.Finding", null)
                    .WithMany()
                    .HasForeignKey("FindingsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_finding_insight_findings_findings_id");

                b.HasOne("Medley.Domain.Entities.Insight", null)
                    .WithMany()
                    .HasForeignKey("InsightsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_finding_insight_insights_insights_id");
            });

            modelBuilder.Entity("FindingObservation", b =>
            {
                b.HasOne("Medley.Domain.Entities.Finding", null)
                    .WithMany()
                    .HasForeignKey("FindingsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_finding_observation_findings_findings_id");

                b.HasOne("Medley.Domain.Entities.Observation", null)
                    .WithMany()
                    .HasForeignKey("ObservationsId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_finding_observation_observations_observations_id");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
            {
                b.HasOne("Medley.Domain.Entities.ArticleType", "ArticleType")
                    .WithMany("Articles")
                    .HasForeignKey("ArticleTypeId")
                    .HasConstraintName("fk_articles_article_types_article_type_id");

                b.HasOne("Medley.Domain.Entities.Article", "ParentArticle")
                    .WithMany("ChildArticles")
                    .HasForeignKey("ParentArticleId")
                    .HasConstraintName("fk_articles_articles_parent_article_id");

                b.Navigation("ArticleType");

                b.Navigation("ParentArticle");
            });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleVersion", b =>
            {
                b.HasOne("Medley.Domain.Entities.Article", "Article")
                    .WithMany()
                    .HasForeignKey("ArticleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_article_versions_articles_article_id");

                b.HasOne("Medley.Domain.Entities.User", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedById")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_article_versions_users_created_by");

                b.Navigation("Article");

                b.Navigation("CreatedBy");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Fragment", b =>
            {
                b.HasOne("Medley.Domain.Entities.Article", null)
                    .WithMany("Fragments")
                    .HasForeignKey("ArticleId")
                    .HasConstraintName("fk_fragments_articles_article_id");

                b.HasOne("Medley.Domain.Entities.Fragment", "ClusteredInto")
                    .WithMany()
                    .HasForeignKey("ClusteredIntoId")
                    .HasConstraintName("fk_fragments_fragments_clustered_into_id");

                b.HasOne("Medley.Domain.Entities.Source", "Source")
                    .WithMany("Fragments")
                    .HasForeignKey("SourceId")
                    .HasConstraintName("fk_fragments_sources_source_id");

                b.Navigation("ClusteredInto");

                b.Navigation("Source");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Observation", b =>
            {
                b.HasOne("Medley.Domain.Entities.ObservationCluster", null)
                    .WithMany("Observations")
                    .HasForeignKey("ObservationClusterId")
                    .HasConstraintName("fk_observations_observation_clusters_observation_cluster_id");

                b.HasOne("Medley.Domain.Entities.Source", "Source")
                    .WithMany("Observations")
                    .HasForeignKey("SourceId")
                    .HasConstraintName("fk_observations_sources_source_id");

                b.Navigation("Source");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
            {
                b.HasOne("Medley.Domain.Entities.Integration", "Integration")
                    .WithMany()
                    .HasForeignKey("IntegrationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_sources_integrations_integration_id");

                b.Navigation("Integration");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Tag", b =>
            {
                b.HasOne("Medley.Domain.Entities.Source", "Source")
                    .WithMany("Tags")
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_tags_sources_source_id");

                b.HasOne("Medley.Domain.Entities.TagOption", "TagOption")
                    .WithMany()
                    .HasForeignKey("TagOptionId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_tags_tag_options_tag_option_id");

                b.HasOne("Medley.Domain.Entities.TagType", "TagType")
                    .WithMany("Tags")
                    .HasForeignKey("TagTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_tags_tag_types_tag_type_id");

                b.Navigation("Source");

                b.Navigation("TagOption");

                b.Navigation("TagType");
            });

            modelBuilder.Entity("Medley.Domain.Entities.TagOption", b =>
            {
                b.HasOne("Medley.Domain.Entities.TagType", "TagType")
                    .WithMany("AllowedValues")
                    .HasForeignKey("TagTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_tag_options_tag_types_tag_type_id");

                b.Navigation("TagType");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.HasOne("Medley.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.HasOne("Medley.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                b.HasOne("Medley.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.HasOne("Medley.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
            {
                b.Navigation("ChildArticles");

                b.Navigation("Fragments");
            });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleType", b =>
            {
                b.Navigation("Articles");
            });

            modelBuilder.Entity("Medley.Domain.Entities.ObservationCluster", b =>
            {
                b.Navigation("Observations");
            });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
            {
                b.Navigation("Fragments");

                b.Navigation("Observations");

                b.Navigation("Tags");
            });

            modelBuilder.Entity("Medley.Domain.Entities.TagType", b =>
            {
                b.Navigation("AllowedValues");

                b.Navigation("Tags");
            });
#pragma warning restore 612, 618
        }
    }
}
