// <auto-generated />
using System;
using Medley.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Medley.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122131053_AddPrimarySpeakerToSource")]
    partial class AddPrimarySpeakerToSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindingInsight", b =>
                {
                    b.Property<Guid>("FindingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("findings_id");

                    b.Property<Guid>("InsightsId")
                        .HasColumnType("uuid")
                        .HasColumnName("insights_id");

                    b.HasKey("FindingsId", "InsightsId")
                        .HasName("pk_finding_insight");

                    b.HasIndex("InsightsId")
                        .HasDatabaseName("ix_finding_insight_insights_id");

                    b.ToTable("finding_insight", (string)null);
                });

            modelBuilder.Entity("FindingObservation", b =>
                {
                    b.Property<Guid>("FindingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("findings_id");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("observations_id");

                    b.HasKey("FindingsId", "ObservationsId")
                        .HasName("pk_finding_observation");

                    b.HasIndex("ObservationsId")
                        .HasDatabaseName("ix_finding_observation_observations_id");

                    b.ToTable("finding_observation", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_type_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ai_prompts");

                    b.HasIndex("ArticleTypeId")
                        .HasDatabaseName("ix_ai_prompts_article_type_id");

                    b.ToTable("ai_prompts", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.AiTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CallStack")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("call_stack");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int?>("EmbeddingTokens")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_tokens");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<string>("OperationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation_name");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_name");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_ai_token_usages");

                    b.HasIndex(new[] { "ModelName" }, "IX_AiTokenUsage_ModelName")
                        .HasDatabaseName("ix_ai_token_usages_model_name");

                    b.HasIndex(new[] { "RelatedEntityType", "RelatedEntityId" }, "IX_AiTokenUsage_RelatedEntity")
                        .HasDatabaseName("ix_ai_token_usages_related_entity_type_related_entity_id");

                    b.HasIndex(new[] { "ServiceName" }, "IX_AiTokenUsage_ServiceName")
                        .HasDatabaseName("ix_ai_token_usages_service_name");

                    b.HasIndex(new[] { "Timestamp" }, "IX_AiTokenUsage_Timestamp")
                        .HasDatabaseName("ix_ai_token_usages_timestamp");

                    b.ToTable("ai_token_usages", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_type_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid?>("CurrentConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_conversation_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ParentArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_article_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("ArticleTypeId")
                        .HasDatabaseName("ix_articles_article_type_id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_articles_assigned_user_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_articles_created_by_id");

                    b.HasIndex("CurrentConversationId")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_current_conversation_id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_articles_current_version_id");

                    b.HasIndex("ParentArticleId")
                        .HasDatabaseName("ix_articles_parent_article_id");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_article_types");

                    b.ToTable("article_types", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("ChangeMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_message");

                    b.Property<string>("ContentDiff")
                        .HasColumnType("text")
                        .HasColumnName("content_diff");

                    b.Property<string>("ContentSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_snapshot");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ParentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_version_id");

                    b.Property<int>("ReviewAction")
                        .HasColumnType("integer")
                        .HasColumnName("review_action");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<int>("VersionType")
                        .HasColumnType("integer")
                        .HasColumnName("version_type");

                    b.HasKey("Id")
                        .HasName("pk_article_versions");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_versions_article_id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_article_versions_conversation_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_article_versions_created_by");

                    b.HasIndex("ParentVersionId")
                        .HasDatabaseName("ix_article_versions_parent_version_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_article_versions_reviewed_by_id");

                    b.HasIndex("VersionType")
                        .HasDatabaseName("ix_article_versions_version_type");

                    b.HasIndex("ArticleId", "CreatedAt")
                        .HasDatabaseName("ix_article_versions_article_id_created_at");

                    b.HasIndex("ArticleId", "VersionNumber", "ParentVersionId", "VersionType")
                        .IsUnique()
                        .HasDatabaseName("ix_article_versions_article_id_version_number_parent_version_i");

                    b.ToTable("article_versions", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("ImplementingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("implementing_plan_id");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_running");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_chat_conversations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_chat_conversations_created_by_user_id");

                    b.HasIndex(new[] { "ArticleId", "State" }, "IX_ChatConversations_ArticleId_State")
                        .HasDatabaseName("ix_chat_conversations_article_id_state");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ChatConversations_CreatedAt")
                        .HasDatabaseName("ix_chat_conversations_created_at");

                    b.HasIndex(new[] { "ImplementingPlanId" }, "IX_ChatConversations_ImplementingPlanId")
                        .HasDatabaseName("ix_chat_conversations_implementing_plan_id");

                    b.ToTable("chat_conversations", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SerializedMessage")
                        .HasColumnType("text")
                        .HasColumnName("serialized_message");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_messages_user_id");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "IX_ChatMessages_ConversationId_CreatedAt")
                        .HasDatabaseName("ix_chat_messages_conversation_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real")
                        .HasColumnName("confidence_score");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Fragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Guid?>("ClusteredIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("clustered_into_id");

                    b.Property<DateTimeOffset?>("ClusteringProcessed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clustering_processed");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("ConfidenceComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("confidence_comment");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(2000)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsCluster")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cluster");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_fragments");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_fragments_article_id");

                    b.HasIndex("ClusteredIntoId")
                        .HasDatabaseName("ix_fragments_clustered_into_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_fragments_source_id");

                    b.ToTable("fragments", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Insight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_insights");

                    b.ToTable("insights", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("InitialSyncCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("initial_sync_completed");

                    b.Property<DateTimeOffset?>("LastHealthCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_health_check_at");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.ToTable("integrations", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real")
                        .HasColumnName("confidence_score");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(2000)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("ObservationClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_cluster_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("ObservationClusterId")
                        .HasDatabaseName("ix_observations_observation_cluster_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_observations_source_id");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.ObservationCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_observation_clusters");

                    b.ToTable("observation_clusters", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailDomain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_domain");

                    b.Property<bool>("EnableSmartTagging")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_smart_tagging");

                    b.Property<bool>("EnableSpeakerExtraction")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_speaker_extraction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("ChangesSummary")
                        .HasColumnType("text")
                        .HasColumnName("changes_summary");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<Guid?>("ParentPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_plan_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_plans_conversation_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_plans_created_by_user_id");

                    b.HasIndex("ParentPlanId")
                        .HasDatabaseName("ix_plans_parent_plan_id");

                    b.HasIndex("ArticleId", "Status")
                        .HasDatabaseName("ix_plans_article_id_status");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.PlanFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FragmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fragment_id");

                    b.Property<bool>("Include")
                        .HasColumnType("boolean")
                        .HasColumnName("include");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reasoning");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.HasKey("Id")
                        .HasName("pk_plan_fragments");

                    b.HasIndex("FragmentId")
                        .HasDatabaseName("ix_plan_fragments_fragment_id");

                    b.HasIndex(new[] { "PlanId", "FragmentId" }, "IX_PlanFragments_PlanId_FragmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_fragments_plan_id_fragment_id");

                    b.ToTable("plan_fragments", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExtractionMessage")
                        .HasColumnType("text")
                        .HasColumnName("extraction_message");

                    b.Property<int>("ExtractionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("extraction_status");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool?>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<int>("MetadataType")
                        .HasColumnType("integer")
                        .HasColumnName("metadata_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PrimarySpeakerId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_speaker_id");

                    b.Property<DateTimeOffset?>("SpeakersExtracted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("speakers_extracted");

                    b.Property<DateTimeOffset?>("TagsGenerated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tags_generated");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_sources_integration_id");

                    b.HasIndex("PrimarySpeakerId")
                        .HasDatabaseName("ix_sources_primary_speaker_id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("TrustLevel")
                        .HasColumnType("integer")
                        .HasColumnName("trust_level");

                    b.HasKey("Id")
                        .HasName("pk_speakers");

                    b.ToTable("speakers", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid?>("TagOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_option_id");

                    b.Property<Guid>("TagTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_type_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("TagOptionId")
                        .HasDatabaseName("ix_tags_tag_option_id");

                    b.HasIndex("TagTypeId")
                        .HasDatabaseName("ix_tags_tag_type_id");

                    b.HasIndex("SourceId", "TagTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_source_id_tag_type_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.TagOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TagTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_type_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tag_options");

                    b.HasIndex("TagTypeId", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_options_tag_type_id_value");

                    b.ToTable("tag_options", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.TagType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsConstrained")
                        .HasColumnType("boolean")
                        .HasColumnName("is_constrained");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<int>("ScopeUpdateMode")
                        .HasColumnType("integer")
                        .HasColumnName("scope_update_mode");

                    b.HasKey("Id")
                        .HasName("pk_tag_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_types_name");

                    b.ToTable("tag_types", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Initials")
                        .HasColumnType("text")
                        .HasColumnName("initials");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Medley.Domain.Entities.UserAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_user_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_user_audit_logs_action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_user_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_audit_logs_user_id");

                    b.ToTable("user_audit_logs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SourceSpeaker", b =>
                {
                    b.Property<Guid>("SourcesId")
                        .HasColumnType("uuid")
                        .HasColumnName("sources_id");

                    b.Property<Guid>("SpeakersId")
                        .HasColumnType("uuid")
                        .HasColumnName("speakers_id");

                    b.HasKey("SourcesId", "SpeakersId")
                        .HasName("pk_source_speakers");

                    b.HasIndex("SpeakersId")
                        .HasDatabaseName("ix_source_speakers_speakers_id");

                    b.ToTable("source_speakers", (string)null);
                });

            modelBuilder.Entity("FindingInsight", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_insight_findings_findings_id");

                    b.HasOne("Medley.Domain.Entities.Insight", null)
                        .WithMany()
                        .HasForeignKey("InsightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_insight_insights_insights_id");
                });

            modelBuilder.Entity("FindingObservation", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_observation_findings_findings_id");

                    b.HasOne("Medley.Domain.Entities.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finding_observation_observations_observations_id");
                });

            modelBuilder.Entity("Medley.Domain.Entities.AiPrompt", b =>
                {
                    b.HasOne("Medley.Domain.Entities.ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("ArticleTypeId")
                        .HasConstraintName("fk_ai_prompts_article_types_article_type_id");

                    b.Navigation("ArticleType");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
                {
                    b.HasOne("Medley.Domain.Entities.ArticleType", "ArticleType")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleTypeId")
                        .HasConstraintName("fk_articles_article_types_article_type_id");

                    b.HasOne("Medley.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_users_assigned_user_id");

                    b.HasOne("Medley.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_users_created_by_id");

                    b.HasOne("Medley.Domain.Entities.ChatConversation", "CurrentConversation")
                        .WithOne()
                        .HasForeignKey("Medley.Domain.Entities.Article", "CurrentConversationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_chat_conversations_current_conversation_id");

                    b.HasOne("Medley.Domain.Entities.ArticleVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_article_versions_current_version_id");

                    b.HasOne("Medley.Domain.Entities.Article", "ParentArticle")
                        .WithMany("ChildArticles")
                        .HasForeignKey("ParentArticleId")
                        .HasConstraintName("fk_articles_articles_parent_article_id");

                    b.Navigation("ArticleType");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedBy");

                    b.Navigation("CurrentConversation");

                    b.Navigation("CurrentVersion");

                    b.Navigation("ParentArticle");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleVersion", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_versions_articles_article_id");

                    b.HasOne("Medley.Domain.Entities.ChatConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_article_versions_chat_conversations_conversation_id");

                    b.HasOne("Medley.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_article_versions_users_created_by");

                    b.HasOne("Medley.Domain.Entities.ArticleVersion", "ParentVersion")
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_article_versions_article_versions_parent_version_id");

                    b.HasOne("Medley.Domain.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_article_versions_users_reviewed_by_id");

                    b.Navigation("Article");

                    b.Navigation("Conversation");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentVersion");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ChatConversation", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Article", "Article")
                        .WithMany("ChatConversations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_conversations_articles_article_id");

                    b.HasOne("Medley.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_conversations_users_created_by_user_id");

                    b.HasOne("Medley.Domain.Entities.Plan", "ImplementingPlan")
                        .WithMany()
                        .HasForeignKey("ImplementingPlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_conversations_plans_implementing_plan_id");

                    b.Navigation("Article");

                    b.Navigation("CreatedBy");

                    b.Navigation("ImplementingPlan");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Medley.Domain.Entities.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_conversations_conversation_id");

                    b.HasOne("Medley.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_messages_users_user_id");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Fragment", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Article", null)
                        .WithMany("Fragments")
                        .HasForeignKey("ArticleId")
                        .HasConstraintName("fk_fragments_articles_article_id");

                    b.HasOne("Medley.Domain.Entities.Fragment", "ClusteredInto")
                        .WithMany()
                        .HasForeignKey("ClusteredIntoId")
                        .HasConstraintName("fk_fragments_fragments_clustered_into_id");

                    b.HasOne("Medley.Domain.Entities.Source", "Source")
                        .WithMany("Fragments")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("fk_fragments_sources_source_id");

                    b.Navigation("ClusteredInto");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Observation", b =>
                {
                    b.HasOne("Medley.Domain.Entities.ObservationCluster", null)
                        .WithMany("Observations")
                        .HasForeignKey("ObservationClusterId")
                        .HasConstraintName("fk_observations_observation_clusters_observation_cluster_id");

                    b.HasOne("Medley.Domain.Entities.Source", "Source")
                        .WithMany("Observations")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("fk_observations_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Plan", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Article", "Article")
                        .WithMany("Plans")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plans_articles_article_id");

                    b.HasOne("Medley.Domain.Entities.ChatConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plans_chat_conversations_conversation_id");

                    b.HasOne("Medley.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plans_users_created_by_user_id");

                    b.HasOne("Medley.Domain.Entities.Plan", "ParentPlan")
                        .WithMany("ChildPlans")
                        .HasForeignKey("ParentPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plans_plans_parent_plan_id");

                    b.Navigation("Article");

                    b.Navigation("Conversation");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentPlan");
                });

            modelBuilder.Entity("Medley.Domain.Entities.PlanFragment", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Fragment", "Fragment")
                        .WithMany("PlanFragments")
                        .HasForeignKey("FragmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_fragments_fragments_fragment_id");

                    b.HasOne("Medley.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanFragments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_fragments_plans_plan_id");

                    b.Navigation("Fragment");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_integrations_integration_id");

                    b.HasOne("Medley.Domain.Entities.Speaker", "PrimarySpeaker")
                        .WithMany()
                        .HasForeignKey("PrimarySpeakerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sources_speakers_primary_speaker_id");

                    b.Navigation("Integration");

                    b.Navigation("PrimarySpeaker");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Source", "Source")
                        .WithMany("Tags")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_sources_source_id");

                    b.HasOne("Medley.Domain.Entities.TagOption", "TagOption")
                        .WithMany()
                        .HasForeignKey("TagOptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_tag_options_tag_option_id");

                    b.HasOne("Medley.Domain.Entities.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tag_types_tag_type_id");

                    b.Navigation("Source");

                    b.Navigation("TagOption");

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("Medley.Domain.Entities.TagOption", b =>
                {
                    b.HasOne("Medley.Domain.Entities.TagType", "TagType")
                        .WithMany("AllowedValues")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_options_tag_types_tag_type_id");

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Medley.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Medley.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Medley.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Medley.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("SourceSpeaker", b =>
                {
                    b.HasOne("Medley.Domain.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_speakers_sources_sources_id");

                    b.HasOne("Medley.Domain.Entities.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_speakers_speakers_speakers_id");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Article", b =>
                {
                    b.Navigation("ChatConversations");

                    b.Navigation("ChildArticles");

                    b.Navigation("Fragments");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ArticleType", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Fragment", b =>
                {
                    b.Navigation("PlanFragments");
                });

            modelBuilder.Entity("Medley.Domain.Entities.ObservationCluster", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Plan", b =>
                {
                    b.Navigation("ChildPlans");

                    b.Navigation("PlanFragments");
                });

            modelBuilder.Entity("Medley.Domain.Entities.Source", b =>
                {
                    b.Navigation("Fragments");

                    b.Navigation("Observations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Medley.Domain.Entities.TagType", b =>
                {
                    b.Navigation("AllowedValues");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
